CREATE DATABASE IF NOT EXISTS REGISTER;

CREATE TABLE IF NOT EXISTS USER_DETAILS (
  ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  USERNAME TEXT DEFAULT NULL,
  PASSWORD TEXT DEFAULT NULL,
  FIRSTNAME TEXT DEFAULT NULL,
  LASTNAME TEXT DEFAULT NULL,
  EMAIL TEXT DEFAULT NULL
);